### PR TITLE
Form validation

### LINKED ISSUE #18: implement form validation on location-edit page

### PR DESCRIPTION
**Pull request by sethvincent**
closes #18

### CODE REVIEW

**Comment by kamicut** [comment]
A couple of comments:
1. Pollutants don't seem to be saved? Is this a regression?
2. It isn't immediately clear what the error is. I would maybe make sure that the required fields have an asterisk next to them, and maybe act on "required" errors by changing the error message to "Make sure to fill in required fields"

**Comment by sethvincent** [comment]
I'll check on the pollutants.

I'd rather do a follow-up pr that tackles error messages in a more comprehensive way. But yeah I agree with that.

**Comment by sethvincent** [comment]
I think the parameters problem had two parts:

1. dependency problem. i've been changing the schema in openaq-data-format over the past couple days and yarn is very specific about which commits it pulls, so i should have mentioned in the pr that a specific commit is needed.
2. the validation checker got confused because it couldn't find the required properties at all in a new instrument, so the latest commit fixed that.

**Comment by sethvincent** [comment]
added asterisks to the labels of required inputs.

**Comment by kamicut** [comment]
@sethvincent I like the new asterisks, I think there is an issue still when clearing pollutants. 
1. Add a new instrument
2. Add pollutant for that instrument
3. Save
4. Re-edit
5. Clear the pollutants in both instruments
6. Save
7. It will go through, the page says that there are no pollutants, but when refreshing, the pollutants are re-added to the instruments 👻

**Pull request merged**
